#!/bin/sh
# postinst script for posnet2-external
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


ETC_DIR=/etc/posnet2-external


case "$1" in
    configure)
    
    	# create a soft link to the .war file, which will change between 
    	# version.
	for i in `find /usr/share/posnet2-external/lib/external-*.war -type f`; do
		ln -sf $i /usr/share/posnet2-external/lib/external.war
	done

	# restore the conf/ symlink
	ln -sf /etc/posnet2-external /usr/share/posnet2-external/conf

	# default firmware directory
	mkdir -p /var/lib/posnet2-external/firmware
    
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


update-rc.d posnet2-external defaults

if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d posnet2-external restart
else
	/etc/init.d/posnet2-external restart
fi

exit 0

